version: '3.8'
services:
  api:

    image: design-blog
    ports:
      - "8080:8080"
    depends_on:
        - db
    environment:
      - SPRING_DATASOURCE_URL =jdbc:postgresql://db:5432/blog
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=1234
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
  db:
    image: postgres:alpine
    ports:
      - "5432:5432"
    environment:
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
      - POSTGRES_DB=blog
      - POSTGRES_HOST_AUTH_METHOD=trust
    healthcheck:
      test: ["CMD-SHELL","pg-isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5